
--TABLA CLIENTES
CREATE TABLE [dbo].[TBL_CLIENTES]
(
	[ID] NVARCHAR(15) NOT NULL PRIMARY KEY,
	[NOMBRE] NVARCHAR(50) NOT NULL,
	[APELLIDO] NVARCHAR(50) NOT NULL,
	[DOB] DATE NOT NULL,
	[EDAD] int NOT NULL,
	[ECIVIL] NVARCHAR(20) NOT NULL,
	[SEXO] NVARCHAR(10) NOT NULL  
);
GO
--INSERT EN  CLIENTES
CREATE PROCEDURE [dbo].[CRE_CLIENTE_PR]
    @P_ID nvarchar(15),
    @P_NOMBRE nvarchar(50),
    @P_APELLIDO nvarchar(50),
    @P_DOB Date,
    @P_EDAD int,
    @P_ECIVIL nvarchar(20),
    @P_SEXO nvarchar(10)
AS
    INSERT INTO [dbo].[TBL_CLIENTES] VALUES(@P_ID,@P_NOMBRE,@P_APELLIDO,@P_DOB,@P_EDAD,@P_ECIVIL,@P_SEXO);

GO
--RETRIEVE ALL CLIENTES
CREATE PROCEDURE [dbo].[RET_ALL_CLIENTES_PR]
AS
    SELECT * FROM TBL_CLIENTES;

GO
--UPDATE CUSTOMER
CREATE PROCEDURE [dbo].[UPD_CLIENTE_PR]
    @P_ID nvarchar(15),
    @P_NOMBRE nvarchar(50),
    @P_APELLIDO nvarchar(50),
    @P_DOB Date,
    @P_EDAD int,
    @P_ECIVIL nvarchar(20),
    @P_SEXO nvarchar(10)
AS
    UPDATE [dbo].[TBL_CLIENTES] SET NOMBRE=@P_NOMBRE, APELLIDO=@P_APELLIDO, DOB=@P_DOB, EDAD=@P_EDAD, ECIVIL=@P_ECIVIL, SEXO=@P_SEXO WHERE ID=@P_ID;
GO
--RET CUSTOMER BY ID
CREATE PROCEDURE [dbo].[RET_CLIENTE_PR]
    @P_ID nvarchar(25)
AS
    SELECT * FROM TBL_CLIENTES WHERE ID=@P_ID;

GO
--DELETE CUSTOMER
CREATE PROCEDURE [dbo].[DEL_CLIENTE_PR]
    @P_ID nvarchar(25)
AS
    DELETE FROM TBL_CLIENTES WHERE ID=@P_ID;

----------------------------------------------------------------------------------------------
--TABLA CREDITOS
CREATE TABLE [dbo].[TBL_CREDITOS]
(
	[IDCREDITO] INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	[IDCLIENTE] NVARCHAR(15) NOT NULL REFERENCES TBL_CLIENTES(ID),
	[MONTO] FLOAT NOT NULL,
	[TASA] FLOAT NOT NULL,
	[NOMBRE] NVARCHAR(50) NOT NULL,
	[CUOTA] FLOAT NOT NULL,
	[FECHA] DATE NOT NULL,
	[ESTADO] NVARCHAR(20) NOT NULL,
	[SALDO] FLOAT NOT NULL
);
GO
--INSERT EN  CREDITOS
CREATE PROCEDURE [dbo].[CRE_CREDITO_PR]
    @P_IDCLIENTE nvarchar(15),
    @P_MONTO FLOAT,
    @P_TASA FLOAT,
    @P_NOMBRE nvarchar(50),
    @P_CUOTA FLOAT,
    @P_FECHA DATE,
    @P_ESTADO nvarchar(20),
    @P_SALDO FLOAT
AS
    INSERT INTO [dbo].[TBL_CREDITOS] VALUES(
   	 @P_IDCLIENTE,@P_MONTO,@P_TASA,@P_NOMBRE,@P_CUOTA,@P_FECHA,@P_ESTADO,@P_SALDO);

GO
--RETRIEVE ALL CREDITOS
CREATE PROCEDURE [dbo].[RET_ALL_CREDITOS_PR]
AS
    SELECT * FROM TBL_CREDITOS;

GO
--RETRIEVE ALL CREDITOS BY ID
CREATE PROCEDURE [dbo].[RET_ALL_CREDITOS_ID_PR]
        @P_IDCLIENTE nvarchar(15)
AS
    SELECT * FROM TBL_CREDITOS WHERE IDCLIENTE=@P_IDCLIENTE;

GO--UPDATE CREDITO
CREATE PROCEDURE [dbo].[UPD_CREDITO_PR]
    @P_IDCREDITO int,
    @P_IDCLIENTE nvarchar(15),
    @P_MONTO FLOAT,
    @P_TASA FLOAT,
    @P_NOMBRE nvarchar(50),
    @P_CUOTA FLOAT,
    @P_FECHA DATE,
    @P_ESTADO nvarchar(20),
    @P_SALDO FLOAT
AS
    UPDATE [dbo].[TBL_CREDITOS] SET IDCLIENTE=@P_IDCLIENTE, MONTO=@P_MONTO,TASA=@P_TASA,NOMBRE=@P_NOMBRE,CUOTA=@P_CUOTA,
   	 FECHA=@P_FECHA,ESTADO=@P_ESTADO,SALDO=@P_SALDO WHERE IDCREDITO=@P_IDCREDITO;

GO--RET CREDITO BY ID
CREATE PROCEDURE [dbo].[RET_CREDITO_PR]
    @P_IDCREDITO int
AS
    SELECT * FROM TBL_CREDITOS WHERE IDCREDITO=@P_IDCREDITO;


GO--DELETE CREDITO
CREATE PROCEDURE [dbo].[DEL_CREDITO_PR]
    @P_IDCREDITO int
AS
    DELETE FROM TBL_CREDITOS WHERE IDCREDITO=@P_IDCREDITO;

----------------------------------------------------------------------------------------------
--TABLA CUENTAS
CREATE TABLE [dbo].[TBL_CUENTAS]
(
	[IDCUENTA] INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	[IDCLIENTE] NVARCHAR(15) NOT NULL REFERENCES TBL_CLIENTES(ID),
	[TIPO] NVARCHAR(50) NOT NULL,
	[MONEDA] NVARCHAR(10) NOT NULL,
	[SALDO] FLOAT NOT NULL
);

GO--INSERT EN  CUENTAS
CREATE PROCEDURE [dbo].[CRE_CUENTA_PR]
    @P_IDCLIENTE nvarchar(15),
    @P_TIPO nvarchar(50),
    @P_MONEDA nvarchar(10),
    @P_SALDO FLOAT
AS
    INSERT INTO [dbo].[TBL_CUENTAS] VALUES(@P_IDCLIENTE,@P_TIPO,@P_MONEDA,@P_SALDO);


GO--RETRIEVE ALL CUENTAS
CREATE PROCEDURE [dbo].[RET_ALL_CUENTAS_PR]
AS
    SELECT * FROM TBL_CUENTAS;

GO--RETRIEVE ALL CUENTAS BY ID
CREATE PROCEDURE [dbo].[RET_ALL_CUENTAS_ID_PR]
    @P_IDCLIENTE nvarchar(15)
AS
    SELECT * FROM TBL_CUENTAS WHERE IDCLIENTE=@P_IDCLIENTE;

GO--UPDATE CUENTA
CREATE PROCEDURE [dbo].[UPD_CUENTA_PR]
    @P_IDCUENTA int,
    @P_IDCLIENTE nvarchar(15),
    @P_TIPO nvarchar(50),
    @P_MONEDA nvarchar(10),
    @P_SALDO FLOAT
AS
    UPDATE [dbo].[TBL_CUENTAS] SET IDCLIENTE=@P_IDCLIENTE, TIPO=@P_TIPO, MONEDA=@P_MONEDA, SALDO=@P_SALDO WHERE IDCUENTA=@P_IDCUENTA;

GO--RET CUENTA BY ID
CREATE PROCEDURE [dbo].[RET_CUENTA_PR]
    @P_IDCUENTA INT
AS
    SELECT * FROM TBL_CUENTAS WHERE IDCUENTA=@P_IDCUENTA;

GO--DELETE CUENTA
CREATE PROCEDURE [dbo].[DEL_CUENTA_PR]
    @P_IDCUENTA INT
AS
    DELETE FROM TBL_CUENTAS WHERE IDCUENTA=@P_IDCUENTA;

----------------------------------------------------------------------------------------------
--TABLA DIRECCIONES
CREATE TABLE [dbo].[TBL_DIRECCIONES]
(	[IDDIRECCION] INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	[IDCLIENTE] NVARCHAR(15) NOT NULL REFERENCES TBL_CLIENTES(ID),
	[PROVINCIA] NVARCHAR(50) NOT NULL,
	[CANTON] NVARCHAR(50) NOT NULL,
	[DISTRITO] NVARCHAR(50) NOT NULL,
	[DETALLES] NVARCHAR(250) NOT NULL
);

GO--INSERT EN  DIRECCIONES
CREATE PROCEDURE [dbo].[CRE_DIRECCION_PR]
    @P_IDCLIENTE nvarchar(15),
    @P_PROVINCIA nvarchar(50),
    @P_CANTON nvarchar(50),
    @P_DISTRITO nvarchar(50),
    @P_DETALLES nvarchar(250)
AS
    INSERT INTO [dbo].[TBL_DIRECCIONES] VALUES(@P_IDCLIENTE,@P_PROVINCIA,@P_CANTON,@P_DISTRITO,@P_DETALLES);


GO--RETRIEVE ALL DIRECCIONES
CREATE PROCEDURE [dbo].[RET_ALL_DIRECCIONES_PR]
AS
    SELECT * FROM TBL_DIRECCIONES;

GO--RETRIEVE ALL DIRECCIONES BY ID
CREATE PROCEDURE [dbo].[RET_ALL_DIRECCIONES_ID_PR]
    @P_IDCLIENTE nvarchar(15)
AS
    SELECT * FROM TBL_DIRECCIONES WHERE IDCLIENTE=@P_IDCLIENTE;

GO--UPDATE DIRECCION
CREATE PROCEDURE [dbo].[UPD_DIRECCION_PR]
    @P_IDDIRECCION int,
    @P_IDCLIENTE nvarchar(15),
    @P_PROVINCIA nvarchar(50),
    @P_CANTON nvarchar(50),
    @P_DISTRITO nvarchar(50),
    @P_DETALLES nvarchar(250)
AS
    UPDATE [dbo].[TBL_DIRECCIONES] SET PROVINCIA=@P_PROVINCIA, CANTON=@P_CANTON, DISTRITO=@P_DISTRITO, DETALLES=@P_DETALLES WHERE IDDIRECCION=@P_IDDIRECCION;

GO--RET DIRECCION BY ID
CREATE PROCEDURE [dbo].[RET_DIRECCION_PR]
    @P_IDDIRECCION int
AS
    SELECT * FROM TBL_DIRECCIONES WHERE IDDIRECCION=@P_IDDIRECCION;

GO--DELETE DIRECCION
CREATE PROCEDURE [dbo].[DEL_DIRECCION_PR]
    @P_IDDIRECCION int
AS
    DELETE FROM TBL_DIRECCIONES WHERE IDDIRECCION=@P_IDDIRECCION;

----------------------------------------------------------------------------------------------
GO--TABLA MOVIMIENTOS
CREATE TABLE [dbo].[TBL_MOVIMIENTOS]
(	[IDMOVIMIENTO] INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	[IDCUENTA] INT NOT NULL REFERENCES TBL_CUENTAS(IDCUENTA),
	[FECHA] DATE NOT NULL,
	[TIPO] NVARCHAR(10) NOT NULL,
	[MONTO] FLOAT NOT NULL
);

GO--INSERT EN  MOVIMIENTOS
CREATE PROCEDURE [dbo].[CRE_MOVIMIENTO_PR]
    @P_IDCUENTA int,
    @P_FECHA DATE,
    @P_TIPO nvarchar(10),
    @P_MONTO FLOAT
AS
    INSERT INTO [dbo].[TBL_MOVIMIENTOS] VALUES(@P_IDCUENTA,@P_FECHA,@P_TIPO,@P_MONTO);

GO--RETRIEVE ALL MOVIMIENTOS
CREATE PROCEDURE [dbo].[RET_ALL_MOVIMIENTOS_PR]
AS
    SELECT * FROM TBL_MOVIMIENTOS;

GO--RETRIEVE ALL MOVIMIENTOS BY ID
CREATE PROCEDURE [dbo].[RET_ALL_MOVIMIENTOS_ID_PR]
    @P_IDCUENTA int
AS
    SELECT * FROM TBL_MOVIMIENTOS WHERE IDCUENTA=@P_IDCUENTA;

GO--UPDATE MOVIMIENTO
CREATE PROCEDURE [dbo].[UPD_MOVIMIENTO_PR]
    @P_IDMOVIMIENTO int,
    @P_IDCUENTA int,
    @P_FECHA DATE,
    @P_TIPO nvarchar(10),
    @P_MONTO FLOAT
AS
    UPDATE [dbo].[TBL_MOVIMIENTOS] SET IDCUENTA=@P_IDCUENTA, FECHA=@P_FECHA, TIPO=@P_TIPO, MONTO=@P_MONTO WHERE IDMOVIMIENTO=@P_IDMOVIMIENTO;

GO--RET MOVIMIENTO BY ID
CREATE PROCEDURE [dbo].[RET_MOVIMIENTO_PR]
    @P_IDMOVIMIENTO int
AS
    SELECT * FROM TBL_MOVIMIENTOS WHERE IDMOVIMIENTO=@P_IDMOVIMIENTO;


GO--DELETE MOVIMIENTO
CREATE PROCEDURE [dbo].[DEL_MOVIMIENTO_PR]
    @P_IDMOVIMIENTO int
AS
    DELETE FROM TBL_MOVIMIENTOS WHERE IDMOVIMIENTO=@P_IDMOVIMIENTO;

----------------------------------------------------------------------------------------------
GO--TABLA PAGOS
CREATE TABLE [dbo].[TBL_PAGOS]
(	[IDPAGO] INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	[IDCREDITO] INT NOT NULL REFERENCES TBL_CREDITOS(IDCREDITO),
	[FECHA] DATE NOT NULL,
	[OPERACION] NVARCHAR(50) NOT NULL,
	[MONTO] FLOAT NOT NULL
);

GO--INSERT EN  PAGOS
CREATE PROCEDURE [dbo].[CRE_PAGO_PR]
    @P_IDCREDITO int,
    @P_FECHA DATE,
    @P_OPERACION nvarchar(50),
    @P_MONTO FLOAT
AS
    INSERT INTO [dbo].[TBL_PAGOS] VALUES(@P_IDCREDITO,@P_FECHA,@P_OPERACION,@P_MONTO);

GO--RETRIEVE ALL PAGOS
CREATE PROCEDURE [dbo].[RET_ALL_PAGOS_PR]
AS
    SELECT * FROM TBL_PAGOS;

GO--RETRIEVE ALL PAGOS BY ID
CREATE PROCEDURE [dbo].[RET_ALL_PAGOS_ID_PR]
    @P_IDCREDITO int
AS
    SELECT * FROM TBL_PAGOS WHERE IDCREDITO=@P_IDCREDITO;

GO--UPDATE PAGO
CREATE PROCEDURE [dbo].[UPD_PAGO_PR]
    @P_IDPAGO int,
    @P_IDCREDITO int,
    @P_FECHA DATE,
    @P_OPERACION nvarchar(50),
    @P_MONTO FLOAT
AS
    UPDATE [dbo].[TBL_PAGOS] SET IDCREDITO=@P_IDCREDITO, FECHA=@P_FECHA, OPERACION=@P_OPERACION, MONTO=@P_MONTO WHERE IDPAGO=@P_IDPAGO;

GO--RET PAGO BY ID
CREATE PROCEDURE [dbo].[RET_PAGO_PR]
    @P_IDPAGO int
AS
    SELECT * FROM TBL_PAGOS WHERE IDPAGO=@P_IDPAGO;

GO--DELETE PAGO
CREATE PROCEDURE [dbo].[DEL_PAGO_PR]
    @P_IDPAGO int
AS
    DELETE FROM TBL_PAGOS WHERE IDPAGO=@P_IDPAGO;

----------------------------------------------------------------------------------------------